# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# This file is the entry point to configure the routes of your app.
# Methods with the #[Route] attribute are automatically imported.
# See also https://symfony.com/doc/current/routing.html

# To list all registered routes, run the following command:
#   bin/console debug:router

controllers:
    resource:
        path: ../src/
        namespace: App\
    type: attribute
    exclude:
        - '../src/Auth/Test/'
        - '../src/Course/Test/'
        - '../src/Frontend/Test/'
        - '../src/OAuth/Test/'
        - '../src/Parser/Test/'
        - '../src/Profile/Test/'
        - '../src/SharedDomain/Test/'
        - '../src/Testing/Test/'

oauth2:
    resource: '@LeagueOAuth2ServerBundle/config/routes.php'
    type: php
